// <auto-generated />
using System;
using BookLibraryRepoPetternCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BookLibraryRepoPetternCore.Migrations
{
    [DbContext(typeof(BookDbContext))]
    [Migration("20240415145551_initial1")]
    partial class initial1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BookLibraryRepoPetternCore.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("BookId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PublishDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Damilare oladele",
                            Description = "Display info about the Book.",
                            Genre = "Asian",
                            PublishDate = new DateTime(2024, 4, 15, 15, 55, 50, 931, DateTimeKind.Local).AddTicks(957),
                            Title = "Eternal secred king"
                        },
                        new
                        {
                            Id = 2,
                            Author = "James wood",
                            Description = "Display info about the Book.",
                            Genre = "Cultivation",
                            PublishDate = new DateTime(2024, 4, 15, 15, 55, 50, 931, DateTimeKind.Local).AddTicks(968),
                            Title = "Legend of swordsMan"
                        },
                        new
                        {
                            Id = 3,
                            Author = "muller james",
                            Description = "Display info about the Book.",
                            Genre = "Cultivation",
                            PublishDate = new DateTime(2024, 4, 15, 15, 55, 50, 931, DateTimeKind.Local).AddTicks(969),
                            Title = "Walker of Worlds"
                        },
                        new
                        {
                            Id = 4,
                            Author = "Ibrahim Oloto",
                            Description = "Display info about the Book.",
                            Genre = "Cultivation",
                            PublishDate = new DateTime(2024, 4, 15, 15, 55, 50, 931, DateTimeKind.Local).AddTicks(971),
                            Title = "Emperor Dominations"
                        },
                        new
                        {
                            Id = 5,
                            Author = "chen Ming",
                            Description = "Display info about the Book.",
                            Genre = "Asian",
                            PublishDate = new DateTime(2024, 4, 15, 15, 55, 50, 931, DateTimeKind.Local).AddTicks(972),
                            Title = "Loaded With Persive Skills"
                        });
                });

            modelBuilder.Entity("BookLibraryRepoPetternCore.Book", b =>
                {
                    b.HasOne("BookLibraryRepoPetternCore.Book", null)
                        .WithMany("books")
                        .HasForeignKey("BookId");
                });

            modelBuilder.Entity("BookLibraryRepoPetternCore.Book", b =>
                {
                    b.Navigation("books");
                });
#pragma warning restore 612, 618
        }
    }
}
